---
title: "Assignment 2"
author: "Jing Tao"
date: "2025-10-01"
format:
  html:
    theme: cosmo
    toc: true
    toc-title: "On this page"
    toc-location: left
    number-sections: true
    css: styles.css
page-layout: article
---

# 1. Run Paul Murrell’s RGraphics basic R programs (murrell01.R)

a.  Run line by line and note the changes\
b.  Pay attention to the comments and answer the questions if any

------------------------------------------------------------------------

## 1) Start plotting from basics (pressure + text)

```{r}
plot(pressure, pch = 16)
text(
  150, 600,
  "Pressure (mm Hg)\nversus\nTemperature (Celsius)"
)
```
```{r}
x  <- c(0.5, 2, 4, 8, 12, 16)
y1 <- c(1, 1.3, 1.9, 3.4, 3.9, 4.8)
y2 <- c(4, 0.8, 0.5, 0.45, 0.4, 0.3)

par(las = 1,
mar = c(4, 4, 2, 4),
cex = .7)

plot.new()
plot.window(range(x), c(0, 6))

lines(x, y1)
lines(x, y2)

points(x, y1, pch = 16, cex = 2)                 # Try different cex?
points(x, y2, pch = 21, bg = "white", cex = 2)   # Different background color

par(col = "gray50", fg = "gray50", col.axis = "gray50")

axis(1, at = seq(0, 16, 4))                      # 1=bottom, 2=left, 3=top, 4=right
axis(2, at = seq(0, 6, 2))
axis(4, at = seq(0, 6, 2))

box(bty = "u")

mtext("Travel Time (s)",      side = 1, line = 2, cex = 0.8)
mtext("Responses per Travel", side = 2, line = 2, las = 0, cex = 0.8)
mtext("Responses per Second", side = 4, line = 2, las = 0, cex = 0.8)

text(4, 5, "Bird 131")

par(
mar      = c(5.1, 4.1, 4.1, 2.1),
col      = "black",
fg       = "black",
col.axis = "black"
)
```

```{r}
# Random data

Y <- rnorm(50)

# Make sure no Y exceed [-3.5, 3.5]

Y[Y < -3.5 | Y > 3.5] <- NA

x  <- seq(-3.5, 3.5, .1)
dn <- dnorm(x)

par(mar = c(4.5, 4.1, 3.1, 0))

hist(
Y,
breaks = seq(-3.5, 3.5),
ylim   = c(0, 0.5),
col    = "gray80",
freq   = FALSE
)

lines(x, dnorm(x), lwd = 2)

par(mar = c(5.1, 4.1, 4.1, 2.1))
```

```{r}
par(mar = c(2, 3.1, 2, 2.1))

midpts <- barplot(
VADeaths,
col   = gray(0.1 + seq(1, 9, 2) / 11),
names = rep("", 4)
)

mtext(
sub(" ", "\n", colnames(VADeaths)),
at   = midpts,
side = 1,
line = 0.5,
cex  = 0.5
)

text(
rep(midpts, each = 5),
apply(VADeaths, 2, cumsum) - VADeaths / 2,
VADeaths,
col = rep(c("white", "black"), times = 3:2),
cex = 0.8
)

par(mar = c(5.1, 4.1, 4.1, 2.1))
```

```{r}
par(mar = c(3, 4.1, 2, 0))

boxplot(
len ~ dose,
data   = ToothGrowth,
boxwex = 0.25,
at     = 1:3 - 0.2,
subset = supp == "VC",
col    = "white",
xlab   = "",
ylab   = "tooth length",
ylim   = c(0, 35)
)

mtext("Vitamin C dose (mg)", side = 1, line = 2.5, cex = 0.8)

boxplot(
len ~ dose,
data   = ToothGrowth,
add    = TRUE,
boxwex = 0.25,
at     = 1:3 + 0.2,
subset = supp == "OJ"
)

legend(
1.5, 9,
c("Ascorbic acid", "Orange juice"),
fill = c("white", "gray"),
bty  = "n"
)

par(mar = c(5.1, 4.1, 4.1, 2.1))
```

```{r}
x <- seq(-10, 10, length = 30)
y <- x

f <- function(x, y) {
r <- sqrt(x^2 + y^2)
10 * sin(r) / r
}

z <- outer(x, y, f)
z[is.na(z)] <- 1

par(mar = c(0, 0.5, 0, 0), lwd = 0.5)
persp(x, y, z, theta = 30, phi = 30, expand = 0.5)
par(mar = c(5.1, 4.1, 4.1, 2.1), lwd = 1)
```

```{r}
par(mar = c(0, 2, 1, 2), xpd = FALSE, cex = 0.5)

pie.sales <- c(0.12, 0.3, 0.26, 0.16, 0.04, 0.12)
names(pie.sales) <- c(
"Blueberry", "Cherry", "Apple",
"Boston Cream", "Other", "Vanilla"
)

pie(
pie.sales,
col = gray(seq(0.3, 1.0, length = 6))
)
```

```{r}
library(readxl)

hpi_path <- "/Users/jingtao/Desktop/FALL 2025/DATA VISUALIZATION/Assignment 2/HPI_2024_public_dataset.xlsx"

df <- tryCatch(
read_excel(hpi_path, sheet = "All Data",        skip = 1),
error = function(e) read_excel(hpi_path, sheet = "1. All countries", skip = 8)
)

# figure out column names for 2 possible sheet layouts

if ("LifeExp" %in% names(df)) {
life_col    <- "LifeExp"                  # All Data
hpi_col     <- "HPI"
country_col <- "Country"
region_col  <- "Continent"
} else {
life_col    <- "Life Expectancy (years)"  # 1. All countries
hpi_col     <- "HPI"
country_col <- "Country"
region_col  <- "Continent"
}

ok    <- complete.cases(df[[life_col]], df[[hpi_col]])
x_le  <- as.numeric(df[[life_col]][ok])   # life expectancy
y_hpi <- as.numeric(df[[hpi_col]][ok])    # HPI score
cty   <- df[[country_col]][ok]
reg   <- df[[region_col]][ok]

length(x_le); length(y_hpi)

head(
data.frame(
country = cty,
lifeexp = x_le,
hpi     = y_hpi
),
6
)
```

```{r}
par(las = 1, mar = c(4, 4, 1.5, 1))
plot(
x_le, y_hpi,
pch  = 16,
xlab = "Life expectancy (years)",
ylab = "HPI score"
)
```

```{r}
plot(
x_le, y_hpi,
pch  = 16,
xlab = "Life expectancy",
ylab = "HPI score"
)

o <- order(x_le)
lines(x_le[o], y_hpi[o], col = "gray80")
```